### ISSUE TITLE
python 3.3 unit test fails on including BeautifulSoup in requirements

### ISSUE THREAD

**Issue by arcolife** [arcolife/scholarec#3]
The following happens on including python 3.3 in .travis.yml : 
- an issue related to a print statement incompatible with python 3.3 (uses " " without brackets):

``` bash
$ pip install -r requirements.txt --use-mirrors
```

_snip_

``` bash
Downloading/unpacking BeautifulSoup==3.2.1 (from -r requirements.txt (line 2))
    Downloading BeautifulSoup-3.2.1.tar.gz
    Running setup.py (path:/home/travis/virtualenv/python3.3/build/BeautifulSoup/setup.py) egg_info for package BeautifulSoup
        Traceback (most recent call last):
        File "<string>", line 17, in <module>
        File "/home/travis/virtualenv/python3.3/build/BeautifulSoup/setup.py", line 22
        print "Unit tests have failed!"
                                      ^

SyntaxError: invalid syntax
Complete output from command python setup.py egg_info:
Traceback (most recent call last):

File "<string>", line 17, in <module>

File "/home/travis/virtualenv/python3.3/build/BeautifulSoup/setup.py", line 22

        print "Unit tests have failed!"
                                      ^

SyntaxError: invalid syntax

----------------------------------------
Cleaning up...
```

**Comment by arcolife** [comment]
no longer using BeautifulSoup==3.2.1
